### ISSUE TITLE
Industrial Foregoing With Animals? 

### ISSUE THREAD

**Issue by HamzaYazaw** [AllTheMods/ATM-4#75]
Hello everyone,
I tried Industrial Foregoing with animals, Apparently the "Animal Rancher", "Sewer" and "Sewage Composer" do not work? Because I can't get Milk out of the cows, and no Sewage from them as well 
You can see the attached screenshots 

![Base Profile Screenshot 2019 12 16 - 16 01 39 43](https://user-images.githubusercontent.com/47602927/70919951-71e88300-202a-11ea-9fd1-b7e8223729dd.png)
![Base Profile Screenshot 2019 12 16 - 16 07 15 05](https://user-images.githubusercontent.com/47602927/70919952-72811980-202a-11ea-8207-2b2f8bb121d9.png)
![Base Profile Screenshot 2019 12 16 - 16 07 20 51](https://user-images.githubusercontent.com/47602927/70919953-72811980-202a-11ea-9465-241692a8899a.png)

**Comment by PABessero** [comment]
For the sewage you need another machine before the composter, since it;s the one that consumes the sewage not creates it

**Comment by HamzaYazaw** [comment]
> For the sewage you need another machine before the composter, since it;s the one that consumes the sewage not creates it

But even the Sewer isn't taking Sewage anyway, 
What is the name of the machine if I may ask? +

**Comment by PABessero** [comment]
Sorry i just came home, it's the Animal Sewer, and from what i saw you need to put the animals on top of it

**Comment by HamzaYazaw** [comment]
> Sorry i just came home, it's the Animal Sewer, and from what i saw you need to put the animals on top of it

No worries! 
Okay I can't find that in the entire mod pack... I can't find "Animal Sewer" inside the modpack
I've read on google that it needs that too, but I don't see it in AllTheMods4

**Comment by PABessero** [comment]
Indeed, it's just called the sewer now (just hopped on ATM4, was going off of memory)

**Comment by HamzaYazaw** [comment]
> Indeed, it's just called the sewer now (just hopped on ATM4, was going off of memory)

Yeah that is what I have installed, which is bizarre why it's not working

**Comment by PABessero** [comment]
Here's the issue from the IF Git, it has been fixed in 2.1.1 and ATM4 is running 2.1.0, so thats probably why its not working
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/636

Edit:
With some luck and if one of the team sees this / the update it will probably be fixed in the next pack update / hotfix

**Comment by HamzaYazaw** [comment]
> Here's the issue from the IF Git, it has been fixed in 2.1.1 and ATM4 is running 2.1.0, so thats probably why its not working
> [InnovativeOnlineIndustries/Industrial-Foregoing#636](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/636)
> 
> Edit:
> With some luck and if one of the team sees this / the update it will probably be fixed in the next pack update / hotfix

Yeah I did some looking up myself too, I noticed that the last time they added Industrial Foregoing was 2.1.0, there a new version of it which is 2.1.2, so i'm hoping it would be fixed next update 

Which is the one that is in now on game version 1.11.2

**Comment by whatthedrunk** [comment]
Was told its fixed in the newest let me know if its still giving issues after todays update.

**Comment by AlexMVW10** [comment]
Sewers appear to still not be working. Unless my game has not updated, but I haven't found out how to check.

**Comment by HamzaYazaw** [comment]
> Sewers appear to still not be working. Unless my game has not updated, but I haven't found out how to check.

They do work, I testes them when I updated my mod, they give you fertilizers but I have no idea how to use fertilizers

**Comment by AlexMVW10** [comment]
I found out how to update, but I may also be able to help you. I haven't tested yet but from experience, I believe you put the fertilizer in the "plant fertilizer" I believe its called, so the order is Sewer makes sewage, turns into fertilizer in the composter, and then used in the plant fertilizer machine on crops in conjunction with the plant gatherer and plant sower.

**Comment by HamzaYazaw** [comment]
> I found out how to update, but I may also be able to help you. I haven't tested yet but from experience, I believe you put the fertilizer in the "plant fertilizer" I believe its called, so the order is Sewer makes sewage, turns into fertilizer in the composter, and then used in the plant fertilizer machine on crops in conjunction with the plant gatherer and plant sower.

I already tried that but it didn't work with me which is weird! 
Let me know what happens with you and I will do the same please
