### ISSUE TITLE
All The Mods 4

### ISSUE THREAD

**Issue by Beamerrrr** [AllTheMods/ATM-4#94]
When we crafted the Botania book on multi player server it show loading error and it you click on the task, it crashes the player. When we tried to make the pure daisy the pedestal would not take the seed.

![image](https://user-images.githubusercontent.com/59294697/71546866-4e3d0b00-294f-11ea-832c-678666edd23a.png)

![image](https://user-images.githubusercontent.com/59294697/71546874-63199e80-294f-11ea-8d58-03807aac032d.png)

**Comment by LezChap** [comment]
I'm not sure what's causing your issue, Botania so far seems to be working as intended for me on the Test Server.  The Lexica (book) is functional so far, and I've got the Petal Apothecary working fine, got it automated for water, Pure Daisies crafted and automated, Endoflames crafted and automated, Magnet Ring and Solegnolia crafted and working (so mana crafting works as far as I've done it), mana pool is full, and a Runic Altar which I've made a rune or two on so that's functioning.  Only major bug I've seen has already been fixed in the code base and should be in the next release, and deals with backend stuff you probably wouldn't see/notice.

**Comment by jellonek** [comment]
I had similar issue with both pure daisy and later with first click on any task in botania book. AFAIR message was saying something about player click handler which caused the crash.
After client restart (I'm doing that in single player world) - I can not reproduce this behavior in the same world.

**Comment by jellonek** [comment]
But... There is an issue with creating the agglomeration plate, as it requires botania block of manasteel while it's not craftable, because of conflict with JAOPCA block of manasteel, which is not allowed in this plate recipe.

**Comment by LezChap** [comment]
> There is an issue with creating the agglomeration plate, as it requires botania block of manasteel while it's not craftable, because of conflict with JAOPCA block of manasteel

That is a conflict.  The solution (for now) is to throw a block of Iron in your mana pool to get a Botania Block of Manasteel.

**Comment by LezChap** [comment]
A more permanent fix to the pack for the Manasteel storage block conflict is as follows:
1. In the configs/jaopca/modules/storage_blocks.toml file, change the blacklist to read:
`	materialBlacklist = ["dragonstone", "elementium", "mana_diamond", "manasteel", "terrasteel"]`
This will remove the JAOPCA version of those blocks.

2. Then, in the configs/jaopca/main.toml file, line 30 to 35 change the customDefined field to say:
`#Configurations related to block tags.
[blockTags]
	#List of block tags that should be considered as defined.
	customDefined = ["dragonstone", "elementium", "mana_diamond", "manasteel", "terrasteel"]
	#List of block tags that should not be added.
	blacklist = []`
This prevents the world from throwing a "blocks missing" warning on every startup after the change from Step 1.

**Comment by Beamerrrr** [comment]
I attached screen shots up top on original post if that helps

**Comment by LezChap** [comment]
I'm having the same error on the test server now, wasn't earlier.  Not sure what caused it yet.

**Comment by Beamerrrr** [comment]
I think it is the one probe. I reloaded the pack and it was working, then I discovered the one probe wasn't so I got the paper and got it to work, then Botania no longer worked. I haven't been able to get it to work again since. Hope this helps

**Comment by LezChap** [comment]
I tried to replicate your suspicions on the conflict between Botania and TheOneProbe and was unable to.  If you can reliably replicate it, please share.

I can say in my testing that it's broken on the server, but works in SinglePlayer, then is broken again when I log into the server...so seems to be something that happens on server/client sync/login.

**Comment by Beamerrrr** [comment]
I was not able to recreate the conflict, but one thing I did notice when looking in the console is there is a memory leak. I did not notice that prior to the last pack update.

**Comment by Skinklizzard** [comment]
I couldn't get the lexicon to work without crashing at all in any single player world from one instance, but created a new fresh instance and just copied the mods over and everything works fine.
I had a look through the logs for the `Error while loading book botania:lexicon` and found its related to a null pointer, seems a recipe in the book is coming back as null. I edited code to work around that and the lexicon works as intended in a single player world on the originally crashing instance but still crashes on either of the two servers I've tried.

I've tried disabling all mods except botania and its dependencies and creating a new world, lexicon would still crash, whatever is causing it appears to be unrelated to the mods or the configs and may be related to internal datapacks or resource locations

The completely new instance with mods copied over appears to work fine connecting to a test server but still client crashes on a server that's been running since previous versions.
Strangely some players on said server don't have an issue

**Comment by Scootz42** [comment]
I'm having pretty much the same issue. The petal apothecary isn't taking seeds and anytime i try to click (every place i've tried so far at least) on an icon in the book it causes my client to crash. i love the pack and i love botania so hopefully someone smarter than myself can figure this out.

edit: i'm also getting the error message about the null pointer

**Comment by williewillus** [comment]
hey all, I released a new botania build earlier today that might solve the problem. let me know if it helps

**Comment by Skinklizzard** [comment]
Unfortunately it doesn't appear to help with this particular problem, the lexicon still fails to load between a remote server and client. I'm not sure if the server recipe list is empty, the server isn't sending the recipes to the client, or the client is failing to get the right message but the lexicon is throwing a null pointer error because the map that would store the recipes is empty.

a singleplayer instance with its integrated server doesn't seem to have this problem so I'd assume the recipes are registering correctly but aren't getting to the client from the remote server.

why it has a communication issue I don't know but it does seem to be effected by the order the mods/datapacks are loaded in as well as the difference between client and server

**Comment by LezChap** [comment]
^ We were having that problem on the ATM4 Test Server.  Haven't been able to track down what "breaks" things (hasn't happened again yet that I'm aware of), but a server restart and it started working again.

**Comment by LezChap** [comment]
We haven't been able to track down why Botania stuff breaks as reported in the OP, but the manasteel block problem brought up by @jellonek (among other storage block conflict issues) should be fixed in 0.3.0.

**Comment by Scootz42** [comment]
Whle it may not be ideal, i created a fresh instance of ATM4 with this newest version (3.0) and everything botania related seems to be working. Lexica Botania is functioning properly so far and am now able to craft with the petal apothecary. will update my old profile later today and check to see if starting a fresh profile had anything to do with it but for now i will botania it up while the going is good ;)
